### ISSUE TITLE
gtpython test failed

### ISSUE THREAD

**Issue by JPascualAnaya** [genometools/genometools#795]
Hi there, 

I was installing genometools and got a single test fail:

```
740: gtpython: unittests                                         : failed
     [ problem: unexpected return code: 1 != 0
       in: /home/champi/Software/genometools/testsuite/stest_testsuite/test740 ]
```

I'm using python 2.6.6 and have added the PYTHONPATH and LD_LIBRARY_PATH variables as indicated in the README file within the gtpython folder to my environment.

Any help would be really appreciated.

Thank you,
Juan

**Comment by satta** [comment]
Hi,

unfortunately I don't have a Python 2.6 installation around to reproduce this easily... but could you tell me a little more about your environment (operating system, GenomeTools version, how did you install?) as well as the exact error messages output by the unit tests (you can find them in the `stderr_*` and/or `stdout_*` files in `/home/champi/Software/genometools/testsuite/stest_testsuite/test740/`).

With Python 2.7 it indeed works fine on my OS X 10.11 machine:
```
$ ./testsuite.rb -keywords gt_python
seed=222018074
723: gtpython: genome_stream bindings (output stream)            : ok
724: gtpython: genome_visitor bindings (output stream)           : ok
725: gtpython: feature_index and feature_stream bindings         : ok
726: gtpython: AnnotationSketch bindings (valid gff3 file)       : ok
727: gtpython: AnnotationSketch bindings (corrupt gff3 file)     : ok
728: gtpython: AnnotationSketch bindings (nonexistent gff3 file) : ok
729: gtpython: AnnotationSketch bindings (simple sketch)         : ok
730: gtpython: AnnotationSketch bindings (PNG stream)            : ok
731: gtpython: AnnotationSketch bindings (TrackSelectorFunc)     : ok
732: gtpython: AnnotationSketch bindings (style)                 : ok
733: gtpython: AnnotationSketch bindings (error reporting)       : ok
734: gtpython: AnnotationSketch bindings (Graphics)              : ok
735: gtpython: AnnotationSketch bindings (FeatureNode(Iterator)) : ok
736: gtpython: show_seqids                                       : ok
737: gtpython: used_types                                        : ok
738: gtpython: show_recmaps                                      : ok
739: gtpython: unicode strings                                   : ok
740: gtpython: unittests                                         : ok
1393: sketch_constructed (Python)                                 : ok
1394: sketch_parsed (Python)                                      : ok
1395: sketch_parsed reverse order (Python)                        : ok
1396: sketch_parsed invalid order (Python, string != int)         : ok
1397: sketch_parsed invalid order (Python, None)                  : ok
1398: Python runtime style failures                               : ok
```

**Comment by JPascualAnaya** [comment]
Thank you for the quick reply! I work on a local server running CenOS6.4, with python 2.6.6. 

gt version:

```
$ gt -version
gt (GenomeTools) 1.5.9
Copyright (c) 2003-2016 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2016 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: cc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3 -Werror
```

`stderr_1` file within the test740 folder:

```
/home/champi/Software/genometools/gtpython/gt/annotationsketch/feature_index.py:21: DeprecationWarning: deprecated
  warnings.warn("deprecated", DeprecationWarning)
/home/champi/Software/genometools/gtpython/gt/annotationsketch/feature_stream.py:21: DeprecationWarning: deprecated
  warnings.warn("deprecated", DeprecationWarning)
........................................................E
======================================================================
ERROR: test_has_version (test_version.VersionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/champi/Software/genometools/gtpython/tests/test_version.py", line 25, in test_has_version
    self.assertIsNotNone(gt.__version__)
AttributeError: 'VersionTest' object has no attribute 'assertIsNotNone'

----------------------------------------------------------------------
Ran 57 tests in 0.129s

FAILED (errors=1)
bug: 24 bytes memory leaked (allocated on line 103 in file "src/core/dlist.c")
```

And what `stest_error` file contains

```
Test 740 'gtpython: unittests': failed:
unexpected return code: 1 != 0:
./stest.rb:286:in `run'
./stest.rb:449:in `run'
testsuite.rb:111:in `run_python'
./gt_python_include.rb:137
./stest.rb:176:in `test'
./stest.rb:165:in `fork'
./stest.rb:165:in `test'
./stest.rb:121:in `process'
./stest.rb:34:in `run'
./stest.rb:27:in `initialize'
./stest.rb:27:in `new'
./stest.rb:27:in `run'
./stest.rb:26:in `upto'
./stest.rb:26:in `run'
testsuite.rb:267
```

In the meanwhile, I will try running the tests changing the python version to the 2.7 and see if that solves the problem.

Thanks!
Juan

**Comment by satta** [comment]
Got it -- the tests use the assertion `assertIsNotNone` which has only been introduced in Python 2.7 (see https://docs.python.org/2.7/library/unittest.html#unittest.TestCase.assertIsNotNone). I guess it should be possible to fix the tests to make them work in 2.6 by just using a different test condition. I will see to it.

**Comment by JPascualAnaya** [comment]
Great. Then, changing to python2.7 will also solve this. 

Thank you!
Juan

**Comment by satta** [comment]
I've put in a pull request for a fix. Feel free to try again once this is merged.
Thanks for reporting this!

**Comment by JPascualAnaya** [comment]
Everything worked fine now. Thanks!
